"""empty message

Revision ID: 10e0928c6e53
Revises: 32bafa4a38cc
Create Date: 2024-12-10 17:50:06.970342

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "10e0928c6e53"
down_revision: Union[str, None] = "32bafa4a38cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "Referrals", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Referrals", type_="unique")
    # ### end Alembic commands ###
