"""empty message

Revision ID: 32bafa4a38cc
Revises: b110a46e4fe7
Create Date: 2024-11-17 19:23:54.584670

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "32bafa4a38cc"
down_revision: Union[str, None] = "b110a46e4fe7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Subscribes", sa.Column("duration_days", sa.Integer(), nullable=False)
    )
    op.add_column(
        "Subscribes", sa.Column("price", sa.Integer(), nullable=False)
    )
    op.add_column(
        "Subscribes", sa.Column("can_referral", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "Subscribes", sa.Column("discount", sa.Integer(), nullable=True)
    )
    op.drop_column("Subscribes", "duration_month")
    op.drop_column("Subscribes", "cost")
    op.add_column(
        "Users", sa.Column("count_referral", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Users", "count_referral")
    op.add_column(
        "Subscribes",
        sa.Column("cost", mysql.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "Subscribes",
        sa.Column(
            "duration_month",
            mysql.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("Subscribes", "discount")
    op.drop_column("Subscribes", "can_referral")
    op.drop_column("Subscribes", "price")
    op.drop_column("Subscribes", "duration_days")
    # ### end Alembic commands ###
