"""end time in user

Revision ID: 4bdd87e8369c
Revises: fde3cab698bc
Create Date: 2024-10-22 14:43:04.230658

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4bdd87e8369c"
down_revision: Union[str, None] = "fde3cab698bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Users", sa.Column("subscribe_end_time", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Users", "subscribe_end_time")
    # ### end Alembic commands ###
