"""empty message

Revision ID: 53a58646c9f1
Revises: 4bdd87e8369c
Create Date: 2024-10-26 13:56:34.469377

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "53a58646c9f1"
down_revision: Union[str, None] = "4bdd87e8369c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Subscribes",
        "duration",
        existing_type=mysql.DATETIME(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Subscribes",
        "duration",
        existing_type=sa.BigInteger(),
        type_=mysql.DATETIME(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
