"""empty message

Revision ID: b110a46e4fe7
Revises: 53a58646c9f1
Create Date: 2024-10-26 14:10:51.889685

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "b110a46e4fe7"
down_revision: Union[str, None] = "53a58646c9f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Subscribes", sa.Column("duration_month", sa.Integer(), nullable=False)
    )
    op.drop_column("Subscribes", "duration")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Subscribes",
        sa.Column(
            "duration", mysql.BIGINT(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("Subscribes", "duration_month")
    # ### end Alembic commands ###
