"""empty message

Revision ID: f6757ff54a5a
Revises: 6ed67191e909
Create Date: 2025-09-15 22:39:08.174816

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "f6757ff54a5a"
down_revision: Union[str, None] = "6ed67191e909"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "groups",
        "global_shift",
        existing_type=mysql.INTEGER(),
        server_default=sa.text("1"),
        existing_nullable=False,
    )
    op.alter_column(
        "subscribes",
        "can_referral",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=sa.text("true"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "count_referral",
        existing_type=mysql.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "is_bot",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "is_premium",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "is_time_shown",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=sa.text("true"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "is_notify",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=sa.text("true"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "is_ban",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    # op.drop_index(op.f('telegram_id'), table_name='users')
    op.create_index(
        op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    # op.create_index(op.f('telegram_id'), 'users', ['telegram_id'], unique=True)
    op.alter_column(
        "users",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "is_ban",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=sa.text("'0'"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "is_notify",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=sa.text("'1'"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "is_time_shown",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=sa.text("'1'"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "is_premium",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=sa.text("'0'"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "is_bot",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=sa.text("'0'"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "count_referral",
        existing_type=mysql.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "subscribes",
        "can_referral",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=sa.text("'1'"),
        existing_nullable=False,
    )
    op.alter_column(
        "groups",
        "global_shift",
        existing_type=mysql.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###
