"""init

Revision ID: fde3cab698bc
Revises:
Create Date: 2024-10-20 22:36:53.103164

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "fde3cab698bc"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
